export enum UrlMappingApi {
    incluir='incluir',
    alterar='alterar',
    buscar='buscar',
    pesquisar='pesquisar',
    deletar='deletar',
    listaLocalidadeRegional='lista-localidade-regional',
    agendarServico='agendar-servico',
    listaServicoPendente='lista-servico-pendente',
    listaDistribuidoUsuario='lista-distribuido-usuario',
    associarServico='associar-servico',
    desassociar='desassociar',
    listaDistribuido='lista-distribuido',
    liberarServico='liberar-servico',
    cancelarLiberacao='cancelar-liberacao',
    listaPerguntaQuestionario='lista-pergunta-questionario',
    listaAlternativaPergunta='lista-alternativa-pergunta',
    alterarSituacaoPergunta='alterar-situacao-pergunta',
    alterarSituacaoQuestionario='alterar-situacao-questionario',
    resetPassword='reset-password',
    // getCoordenadas='get-coordenadas',
    listaColaboradorSemVeiculo='lista-colaborador-sem-veiculo',
    getRespostas='get-respostas',
    getRetornoFotos= 'get-retorno-foto',
    getFoto='getfoto'
}
